# Generated by Django 4.2.3 on 2023-07-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Assigent_employeename',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
